# Generated by Django 4.0.4 on 2022-05-31 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstorage', '0002_fileinfo_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='key',
            field=models.TextField(max_length=40, null=True),
        ),
    ]
