# Generated by Django 4.0.4 on 2022-06-04 19:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloudstorage', '0003_fileinfo_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='path',
            field=models.TextField(default='/', max_length=100),
        ),
        migrations.CreateModel(
            name='FolderTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tree', models.JSONField(default="{'root':{}}")),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
