# Generated by Django 4.0.4 on 2022-06-04 21:30

import cloudstorage.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cloudstorage', '0004_fileinfo_path_foldertree'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileinfo',
            old_name='path',
            new_name='file_path',
        ),
        migrations.AlterField(
            model_name='fileinfo',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foldertree',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='foldertree',
            name='tree',
            field=models.JSONField(default=cloudstorage.models.get_default_tree),
        ),
    ]
