# Generated by Django 4.0.5 on 2022-06-06 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cloudstorage', '0005_rename_path_fileinfo_file_path_alter_fileinfo_owner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileinfo',
            name='script',
            field=models.TextField(blank=True, null=True, verbose_name='동영상 스크립트'),
        ),
    ]
